parameters:
#    mqm_upgrade.example.class: MQM\UpgradeBundle\Example

services:
#    mqm_upgrade.example:
#        class: %mqm_upgrade.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
